CREATE TABLE IF NOT EXISTS country (
  id_country int(11) NOT NULL auto_increment,
  name varchar(100) NOT NULL default '',
  PRIMARY KEY  (id_country)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
INSERT INTO country (id_country, name) VALUES (1, 'United States');
INSERT INTO country (id_country, name) VALUES (2, 'Albania');
INSERT INTO country (id_country, name) VALUES (3, 'Algeria');
INSERT INTO country (id_country, name) VALUES (4, 'American Samoa');
INSERT INTO country (id_country, name) VALUES (5, 'Andorra');
INSERT INTO country (id_country, name) VALUES (6, 'Angola');
INSERT INTO country (id_country, name) VALUES (7, 'Anguilla');
INSERT INTO country (id_country, name) VALUES (8, 'Antarctica');
INSERT INTO country (id_country, name) VALUES (9, 'Antigua And Barbuda');
INSERT INTO country (id_country, name) VALUES (10, 'Argentina');
INSERT INTO country (id_country, name) VALUES (11, 'Armenia');
INSERT INTO country (id_country, name) VALUES (12, 'Aruba');
INSERT INTO country (id_country, name) VALUES (13, 'Australia');
INSERT INTO country (id_country, name) VALUES (14, 'Austria');
INSERT INTO country (id_country, name) VALUES (15, 'Azerbaijan');
INSERT INTO country (id_country, name) VALUES (16, 'Bahamas');
INSERT INTO country (id_country, name) VALUES (17, 'Bahrain');
INSERT INTO country (id_country, name) VALUES (18, 'Bangladesh');
INSERT INTO country (id_country, name) VALUES (19, 'Barbados');
INSERT INTO country (id_country, name) VALUES (20, 'Belarus');
INSERT INTO country (id_country, name) VALUES (21, 'Belgium');
INSERT INTO country (id_country, name) VALUES (22, 'Belize');
INSERT INTO country (id_country, name) VALUES (23, 'Benin');
INSERT INTO country (id_country, name) VALUES (24, 'Bermuda');
INSERT INTO country (id_country, name) VALUES (25, 'Bhutan');
INSERT INTO country (id_country, name) VALUES (26, 'Bolivia');
INSERT INTO country (id_country, name) VALUES (27, 'Bosnia and Herzegovina');
INSERT INTO country (id_country, name) VALUES (28, 'Botswana');
INSERT INTO country (id_country, name) VALUES (29, 'Bouvet Island');
INSERT INTO country (id_country, name) VALUES (30, 'Brazil');
INSERT INTO country (id_country, name) VALUES (31, 'British Indean Ocean Territory');
INSERT INTO country (id_country, name) VALUES (32, 'Brunei Darussalam');
INSERT INTO country (id_country, name) VALUES (33, 'Bulgaria');
INSERT INTO country (id_country, name) VALUES (34, 'Burkina Faso');
INSERT INTO country (id_country, name) VALUES (35, 'Burundi');
INSERT INTO country (id_country, name) VALUES (36, 'Cambodia');
INSERT INTO country (id_country, name) VALUES (37, 'Cameroon');
INSERT INTO country (id_country, name) VALUES (38, 'Canada');
INSERT INTO country (id_country, name) VALUES (39, 'Cape Verde');
INSERT INTO country (id_country, name) VALUES (40, 'Cayman Islands');
INSERT INTO country (id_country, name) VALUES (41, 'Central African Republic');
INSERT INTO country (id_country, name) VALUES (42, 'Chad');
INSERT INTO country (id_country, name) VALUES (43, 'Chile');
INSERT INTO country (id_country, name) VALUES (44, 'China');
INSERT INTO country (id_country, name) VALUES (45, 'Christmas Island');
INSERT INTO country (id_country, name) VALUES (46, 'Cocos (Keeling) Islands');
INSERT INTO country (id_country, name) VALUES (47, 'Colombia');
INSERT INTO country (id_country, name) VALUES (48, 'Comoros');
INSERT INTO country (id_country, name) VALUES (49, 'Congo');
INSERT INTO country (id_country, name) VALUES (50, 'Congo, The Dem. Rep. Of The');
INSERT INTO country (id_country, name) VALUES (51, 'Cook Islands');
INSERT INTO country (id_country, name) VALUES (52, 'Costa Rica');
INSERT INTO country (id_country, name) VALUES (53, 'Cote d.Ivoire');
INSERT INTO country (id_country, name) VALUES (54, 'Croatia');
INSERT INTO country (id_country, name) VALUES (55, 'Cyprus');
INSERT INTO country (id_country, name) VALUES (56, 'Czech Republic');
INSERT INTO country (id_country, name) VALUES (57, 'Denmark');
INSERT INTO country (id_country, name) VALUES (58, 'Djibouti');
INSERT INTO country (id_country, name) VALUES (59, 'Dominica');
INSERT INTO country (id_country, name) VALUES (60, 'Dominican Republic');
INSERT INTO country (id_country, name) VALUES (61, 'East Timor');
INSERT INTO country (id_country, name) VALUES (62, 'Ecuador');
INSERT INTO country (id_country, name) VALUES (63, 'Egypt');
INSERT INTO country (id_country, name) VALUES (64, 'El Salvador');
INSERT INTO country (id_country, name) VALUES (65, 'Equatorial Guinea');
INSERT INTO country (id_country, name) VALUES (66, 'Eritrea');
INSERT INTO country (id_country, name) VALUES (67, 'Estonia');
INSERT INTO country (id_country, name) VALUES (68, 'Ethiopia');
INSERT INTO country (id_country, name) VALUES (69, 'Falkland Islands (Malvinas)');
INSERT INTO country (id_country, name) VALUES (70, 'Faroe Islands');
INSERT INTO country (id_country, name) VALUES (71, 'Fiji');
INSERT INTO country (id_country, name) VALUES (72, 'Finland');
INSERT INTO country (id_country, name) VALUES (73, 'France');
INSERT INTO country (id_country, name) VALUES (74, 'French Guiana');
INSERT INTO country (id_country, name) VALUES (75, 'French Polynesia');
INSERT INTO country (id_country, name) VALUES (76, 'French Southern Territories');
INSERT INTO country (id_country, name) VALUES (77, 'Gabon');
INSERT INTO country (id_country, name) VALUES (78, 'Gambia');
INSERT INTO country (id_country, name) VALUES (79, 'Georgia');
INSERT INTO country (id_country, name) VALUES (80, 'Germany');
INSERT INTO country (id_country, name) VALUES (81, 'Ghana');
INSERT INTO country (id_country, name) VALUES (82, 'Gibraltar');
INSERT INTO country (id_country, name) VALUES (83, 'Greece');
INSERT INTO country (id_country, name) VALUES (84, 'Greenland');
INSERT INTO country (id_country, name) VALUES (85, 'Grenada');
INSERT INTO country (id_country, name) VALUES (86, 'Guadeloupe');
INSERT INTO country (id_country, name) VALUES (87, 'Guam');
INSERT INTO country (id_country, name) VALUES (88, 'Guatemala');
INSERT INTO country (id_country, name) VALUES (89, 'Guinea');
INSERT INTO country (id_country, name) VALUES (90, 'Guinea-Bissau');
INSERT INTO country (id_country, name) VALUES (91, 'Guyana');
INSERT INTO country (id_country, name) VALUES (92, 'Haiti');
INSERT INTO country (id_country, name) VALUES (93, 'Heard And Mcdonald Islands');
INSERT INTO country (id_country, name) VALUES (94, 'Honduras');
INSERT INTO country (id_country, name) VALUES (95, 'Hong Kong');
INSERT INTO country (id_country, name) VALUES (96, 'Hungary');
INSERT INTO country (id_country, name) VALUES (97, 'Iceland');
INSERT INTO country (id_country, name) VALUES (98, 'India');
INSERT INTO country (id_country, name) VALUES (99, 'Indonesia');
INSERT INTO country (id_country, name) VALUES (100, 'Ireland');
INSERT INTO country (id_country, name) VALUES (101, 'Iran, Islamic Republic Of');
INSERT INTO country (id_country, name) VALUES (102, 'Iraq');
INSERT INTO country (id_country, name) VALUES (103, 'Israel');
INSERT INTO country (id_country, name) VALUES (104, 'Italy');
INSERT INTO country (id_country, name) VALUES (105, 'Jamaica');
INSERT INTO country (id_country, name) VALUES (106, 'Japan');
INSERT INTO country (id_country, name) VALUES (107, 'Jordan');
INSERT INTO country (id_country, name) VALUES (108, 'Kazakstan');
INSERT INTO country (id_country, name) VALUES (109, 'Kenya');
INSERT INTO country (id_country, name) VALUES (110, 'Kiribati');
INSERT INTO country (id_country, name) VALUES (111, 'Korea, Dem. Rep. Of');
INSERT INTO country (id_country, name) VALUES (112, 'Korea, Republic Of');
INSERT INTO country (id_country, name) VALUES (113, 'Kuwait');
INSERT INTO country (id_country, name) VALUES (114, 'Kyrgyzstan');
INSERT INTO country (id_country, name) VALUES (115, 'Laos People.s Dem. Rep.');
INSERT INTO country (id_country, name) VALUES (116, 'Latvia');
INSERT INTO country (id_country, name) VALUES (117, 'Lebanon');
INSERT INTO country (id_country, name) VALUES (118, 'Lesotho');
INSERT INTO country (id_country, name) VALUES (119, 'Liberia');
INSERT INTO country (id_country, name) VALUES (120, 'Liechtenstein');
INSERT INTO country (id_country, name) VALUES (121, 'Lithuania');
INSERT INTO country (id_country, name) VALUES (122, 'Luxembourg');
INSERT INTO country (id_country, name) VALUES (123, 'Libyan Arab Jamahiriya');
INSERT INTO country (id_country, name) VALUES (124, 'Macau');
INSERT INTO country (id_country, name) VALUES (125, 'Macedonia');
INSERT INTO country (id_country, name) VALUES (126, 'Madagascar');
INSERT INTO country (id_country, name) VALUES (127, 'Malawi');
INSERT INTO country (id_country, name) VALUES (128, 'Malaysia');
INSERT INTO country (id_country, name) VALUES (129, 'Maldives');
INSERT INTO country (id_country, name) VALUES (130, 'Mali');
INSERT INTO country (id_country, name) VALUES (131, 'Malta');
INSERT INTO country (id_country, name) VALUES (132, 'Marshall Islands');
INSERT INTO country (id_country, name) VALUES (133, 'Martinique');
INSERT INTO country (id_country, name) VALUES (134, 'Mauritania');
INSERT INTO country (id_country, name) VALUES (135, 'Mauritius');
INSERT INTO country (id_country, name) VALUES (136, 'Mayotte');
INSERT INTO country (id_country, name) VALUES (137, 'Mexico');
INSERT INTO country (id_country, name) VALUES (138, 'Micronesia, Federated States Of');
INSERT INTO country (id_country, name) VALUES (139, 'Moldova, Republic Of');
INSERT INTO country (id_country, name) VALUES (140, 'Monaco');
INSERT INTO country (id_country, name) VALUES (141, 'Mongolia');
INSERT INTO country (id_country, name) VALUES (142, 'Montserrat');
INSERT INTO country (id_country, name) VALUES (143, 'Morocco');
INSERT INTO country (id_country, name) VALUES (144, 'Mozambique');
INSERT INTO country (id_country, name) VALUES (145, 'Myanmar');
INSERT INTO country (id_country, name) VALUES (146, 'Namibia');
INSERT INTO country (id_country, name) VALUES (147, 'Nauru');
INSERT INTO country (id_country, name) VALUES (148, 'Nepal');
INSERT INTO country (id_country, name) VALUES (149, 'Netherlands');
INSERT INTO country (id_country, name) VALUES (150, 'Netherlands Antilles');
INSERT INTO country (id_country, name) VALUES (151, 'New Caledonia');
INSERT INTO country (id_country, name) VALUES (152, 'New Zealand');
INSERT INTO country (id_country, name) VALUES (153, 'Nicaragua');
INSERT INTO country (id_country, name) VALUES (154, 'Niger');
INSERT INTO country (id_country, name) VALUES (155, 'Nigeria');
INSERT INTO country (id_country, name) VALUES (156, 'Niue');
INSERT INTO country (id_country, name) VALUES (157, 'Norfolk Island');
INSERT INTO country (id_country, name) VALUES (158, 'Northern Mariana Islands');
INSERT INTO country (id_country, name) VALUES (159, 'Norway');
INSERT INTO country (id_country, name) VALUES (160, 'Oman');
INSERT INTO country (id_country, name) VALUES (161, 'Pakistan');
INSERT INTO country (id_country, name) VALUES (162, 'Palau');
INSERT INTO country (id_country, name) VALUES (163, 'Panama');
INSERT INTO country (id_country, name) VALUES (164, 'Papua New Guinea');
INSERT INTO country (id_country, name) VALUES (165, 'Paraguay');
INSERT INTO country (id_country, name) VALUES (166, 'Peru');
INSERT INTO country (id_country, name) VALUES (167, 'Philippines');
INSERT INTO country (id_country, name) VALUES (168, 'Pitcairn');
INSERT INTO country (id_country, name) VALUES (169, 'Poland');
INSERT INTO country (id_country, name) VALUES (170, 'Portugal');
INSERT INTO country (id_country, name) VALUES (171, 'Puerto Rico');
INSERT INTO country (id_country, name) VALUES (172, 'Qatar');
INSERT INTO country (id_country, name) VALUES (173, 'Reunion');
INSERT INTO country (id_country, name) VALUES (174, 'Romania');
INSERT INTO country (id_country, name) VALUES (175, 'Russian Federation');
INSERT INTO country (id_country, name) VALUES (176, 'Rwanda');
INSERT INTO country (id_country, name) VALUES (177, 'Saint Kitts And Nevis');
INSERT INTO country (id_country, name) VALUES (178, 'Saint Lucia');
INSERT INTO country (id_country, name) VALUES (179, 'Saint Vincent And The Grenadines');
INSERT INTO country (id_country, name) VALUES (180, 'Samoa');
INSERT INTO country (id_country, name) VALUES (181, 'San Marino');
INSERT INTO country (id_country, name) VALUES (182, 'Sao Tome And Principe');
INSERT INTO country (id_country, name) VALUES (183, 'Saudi Arabia');
INSERT INTO country (id_country, name) VALUES (184, 'Senegal');
INSERT INTO country (id_country, name) VALUES (185, 'Seychelles');
INSERT INTO country (id_country, name) VALUES (186, 'Sierra Leone');
INSERT INTO country (id_country, name) VALUES (187, 'Singapore');
INSERT INTO country (id_country, name) VALUES (188, 'Slovakia');
INSERT INTO country (id_country, name) VALUES (189, 'Slovenia');
INSERT INTO country (id_country, name) VALUES (190, 'Solomon Islands');
INSERT INTO country (id_country, name) VALUES (191, 'Somalia');
INSERT INTO country (id_country, name) VALUES (192, 'South Africa');
INSERT INTO country (id_country, name) VALUES (193, 'South Georgia');
INSERT INTO country (id_country, name) VALUES (194, 'Spain');
INSERT INTO country (id_country, name) VALUES (195, 'Sri Lanka');
INSERT INTO country (id_country, name) VALUES (196, 'Saint Helena');
INSERT INTO country (id_country, name) VALUES (197, 'Saint Pierre And Miquelon');
INSERT INTO country (id_country, name) VALUES (198, 'Suriname');
INSERT INTO country (id_country, name) VALUES (199, 'Svalbard and Jan Mayen');
INSERT INTO country (id_country, name) VALUES (200, 'Swaziland');
INSERT INTO country (id_country, name) VALUES (201, 'Sweden');
INSERT INTO country (id_country, name) VALUES (202, 'Switzerland');
INSERT INTO country (id_country, name) VALUES (203, 'Syrian Arab Republic');
INSERT INTO country (id_country, name) VALUES (204, 'Taiwan');
INSERT INTO country (id_country, name) VALUES (205, 'Tajikistan');
INSERT INTO country (id_country, name) VALUES (206, 'Tanzania, United Republic Of');
INSERT INTO country (id_country, name) VALUES (207, 'Thailand');
INSERT INTO country (id_country, name) VALUES (208, 'Togo');
INSERT INTO country (id_country, name) VALUES (209, 'Tokelau');
INSERT INTO country (id_country, name) VALUES (210, 'Tonga');
INSERT INTO country (id_country, name) VALUES (211, 'Trinidad and Tobago');
INSERT INTO country (id_country, name) VALUES (212, 'Tunisia');
INSERT INTO country (id_country, name) VALUES (213, 'Turkey');
INSERT INTO country (id_country, name) VALUES (214, 'Turkmenistan');
INSERT INTO country (id_country, name) VALUES (215, 'Turks and Caicos Islands');
INSERT INTO country (id_country, name) VALUES (216, 'Tuvalu');
INSERT INTO country (id_country, name) VALUES (217, 'Uganda');
INSERT INTO country (id_country, name) VALUES (218, 'Ukraine');
INSERT INTO country (id_country, name) VALUES (219, 'United Arab Emirates');
INSERT INTO country (id_country, name) VALUES (220, 'United Kingdom');
INSERT INTO country (id_country, name) VALUES (221, 'United States Minor Outlying Islands');
INSERT INTO country (id_country, name) VALUES (222, 'Uruguay');
INSERT INTO country (id_country, name) VALUES (223, 'Uzbekistan');
INSERT INTO country (id_country, name) VALUES (224, 'Vanuatu');
INSERT INTO country (id_country, name) VALUES (225, 'Holy See (Vatican City State)');
INSERT INTO country (id_country, name) VALUES (226, 'Venezuela');
INSERT INTO country (id_country, name) VALUES (227, 'Viet Nam');
INSERT INTO country (id_country, name) VALUES (228, 'Virgin Islands, British');
INSERT INTO country (id_country, name) VALUES (229, 'Virgin Islands, US');
INSERT INTO country (id_country, name) VALUES (230, 'Wallis And Futuna');
INSERT INTO country (id_country, name) VALUES (231, 'Western Sahara');
INSERT INTO country (id_country, name) VALUES (232, 'Yugoslavia');
INSERT INTO country (id_country, name) VALUES (233, 'Yemen');
INSERT INTO country (id_country, name) VALUES (234, 'Zambia');
INSERT INTO country (id_country, name) VALUES (235, 'Zimbabwe');
INSERT INTO country (id_country, name) VALUES (236, 'Cuba');
INSERT INTO country (id_country, name) VALUES (237, 'Afghanistan');
INSERT INTO country (id_country, name) VALUES (238, 'Palestinian Territory');
INSERT INTO country (id_country, name) VALUES (239, 'Sudan');